### PR TITLE
AUI-3178 In Calendar's monthly view, when today's date is the last week of the month, the blue border is cut out

### PR DESCRIPTION
**Pull request by knchau**
https://issues.liferay.com/browse/AUI-3178

LPS Issue: https://issues.liferay.com/browse/LPS-102368

https://github.com/holatuwol/alloy-ui/commit/9f83d06426ae1f391a3e37faaf7de4f107666371 fixes edge case when today's date is the first cell of the month.

### CODE REVIEW

**Comment by holatuwol** [comment]
@knchau : Instead of adding the sameDay function, could you instead add a `betweenInclusive` function that matches the start date, end date, or between?

**Comment by knchau** [comment]
@holatuwol : I've added the `betweenInclusive` function, but I also added an `equal` function to compare the times if they are equal. Let me know if that is sufficient change or not, thank you!

**Comment by holatuwol** [comment]
@knchau : Isn't the `equal` function the same as the already-existing `compare` function?

**Comment by knchau** [comment]
@holatuwol : Thanks for pointing that out, I didn't notice that!

**Comment by holatuwol** [comment]
https://github.com/jonmak08/alloy-ui/pull/447

**Pull request closed without merging**
